### ISSUE TITLE
Add a "mammoth fresh" or similar for new installations

### ISSUE THREAD

**Issue by voxpelli** [Ff00ff/mammoth-cli#3]
When doing fresh installations I much rather just install the defined tables as is rather than running through possibly years of migrations. Would love to be able to do that here as well.

I made an extension to the knex migrator which did that many years ago: https://github.com/voxpelli/node-knex-migrator-extension (Based on a PR I suggested to knex: https://github.com/knex/knex/pull/617)

I've used it in eg: https://github.com/voxpelli/webpage-webmentions/blob/3ec2e8ac25b436ffe75d6f9fb51b2f63906d650c/knexfile.js#L10-L13 Where I had a reference schema setup, like you do here with Mammoth: https://github.com/voxpelli/webpage-webmentions/blob/master/lib/install-schema.js

I had two commands, one for fresh installs and one for migrating existing installs: https://github.com/voxpelli/webpage-webmentions/blob/3ec2e8ac25b436ffe75d6f9fb51b2f63906d650c/package.json#L56-L57

Now I'm looking at moving to something more modern and maintainable than that, and I really liked Mammoth at the first look, so I'm probably going to be giving some thoughts and PR:s here.

**Comment by martijndeh** [comment]
Before I give a more in depth reply: why don’t you want to run through possibly years of migrations?

**Comment by voxpelli** [comment]
1. Speed, eg in tests where I want to tear down and set up the tables over and over, but also in general: Setting up a new installation needs to run nothing more than the relevant schema creations + initialize the migration table to indicate with what migration it is in sync.
2. Creates a too big dependency on old migrations and of every migration being a 100% perfect. Becomes especially apparent if #4 gets implemented, where migrations can be so much more than simple schema changes.

**Comment by martijndeh** [comment]
Yes, these are very real problems, I agree. But a fresh command, as you’re suggesting, isn’t the only solution:

1. In a test you could run the migrations once and truncate all tables after every run. Or if you need something more advanced you could create a database template and create a new database based on the template. This should be very fast. This is not the scope of the main query builder or the cli but it could be of a supporting test library.
2. When old migrations become too much of a burden, other tools allow you to squash migrations. This basically means merging migrations into one and remove unnecessary sql statements. This is not supported yet. Django has some clear documentation on this.

A fresh command would mean its possible to build the database schema in a different way and that could cause issues. There is plenty of work to be done on the remaining of Mammoth so at this time I don’t think a fresh command is a good idea.
